import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));const c={crypto:webcrypto};vm.createContext(c);vm.runInContext(fs.readFileSync(root+'public/luck-v2.js','utf8')+';this.luck=WHEEL_LUCK;',c);vm.runInContext(fs.readFileSync(root+'public/data-v2.js','utf8')+';this.data=WHEEL_DATA;',c);const L=c.luck,D=c.data;
const boundary=Object.fromEntries(L.tiers.map(t=>[t.id,0]));for(let ticket=0;ticket<100;ticket++)boundary[L.roll(()=>ticket)]++;assert.deepEqual(boundary,{common:50,uncommon:25,rare:15,unique:6,legendary:3,mythic:1});
const base=JSON.stringify(D),all=[...Object.values(D.base),...Object.values(D.subrace),...Object.values(D.subclass)];
for(const options of all){let previous=-Infinity;for(const tier of L.tiers){const weighted=L.biasOptions(options,tier.id),sum=weighted.reduce((s,o)=>s+o.weight,0),expected=weighted.reduce((s,o)=>s+o.weight*o.stats.reduce((n,v)=>n+v,0),0)/sum;assert(expected>=previous-.002,`${tier.id} lowered expected trait score`);previous=expected;assert(weighted.every(o=>Number.isSafeInteger(o.weight)&&o.weight>0));assert.deepEqual(weighted.map(o=>o.stats),options.map(o=>o.stats));}}
assert.equal(JSON.stringify(D),base);
for(const tier of L.tiers)for(const points of [0,3,8,25,65,400]){const options=L.powerOptions(D.base.power,'power',tier.id,points),sum=options.reduce((s,o)=>s+o.weight,0),power=options.filter(o=>!/^no (second )?power$/i.test(o.name)).reduce((s,o)=>s+o.weight,0);assert(Math.abs(power/sum*100-L.magicChance(points))<1e-8);assert(Number.isSafeInteger(sum));const second=L.powerOptions(D.base.power2,'power2',tier.id,points,'Fire manipulation');assert(second.every(o=>o.name!=='Fire manipulation'));}
const histogram=Object.fromEntries(L.tiers.map(t=>[t.id,0]));for(let i=0;i<100000;i++)histogram[L.roll()]++;for(const t of L.tiers){const expected=t.chance*1000,sd=Math.sqrt(100000*(t.chance/100)*(1-t.chance/100));assert(Math.abs(histogram[t.id]-expected)<6*sd);}
let seed=123456789;const rand=n=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return Math.floor((seed>>>0)/4294967296*n);};let start=0;const averages={};
for(const t of L.tiers){let sum=0;for(let i=0;i<2000;i++){let first=true;const r=L.rollTraits(D,n=>{if(first){first=false;return start;}return rand(n);});assert.equal(r.wheelRarity,t.id);let stats=[0,0,0,0,0];for(const [id,name]of Object.entries(r.traits)){if(/^no (second )?power$/i.test(name))continue;const options=id==='subrace'?D.subrace[r.traits.race]:id==='subclass'?D.subclass[r.traits.class]:D.base[id];options.find(o=>o.name===name).stats.forEach((v,k)=>stats[k]+=v);}sum+=stats.reduce((s,v)=>s+Math.max(0,v),0);}averages[t.id]=Math.round(sum/2000);start+=t.chance;}
const means=Object.values(averages);assert(means.every((m,i)=>!i||m>means[i-1]));
console.log(JSON.stringify({exactRarityOdds:boundary,random100000Rolls:histogram,meanTotalFrom2000CharactersPerRarity:averages,checks:'all trait tables improve or retain expected score; unchanged stats and base weights; Magic odds preserved; no duplicate powers'}));
