import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {DatabaseSync} from 'node:sqlite';
import {assertSeriesResult,seriesComplete} from '../public/series.js';import {defaultStage,createTournament,nextMatch,recordMatch,resolveMatch} from '../public/tournaments.js';import worker from '../dist/server/index.js';
const games=winners=>winners.map(winner=>({winner,seconds:1}));
assert.deepEqual(assertSeriesResult({bestOf:3,allowDraw:true},[{winner:'a',seconds:1},{winner:null,seconds:90},{winner:'b',seconds:1}],'a','b'),[1,1]);
assert.deepEqual(assertSeriesResult({bestOf:1,allowDraw:true},[{winner:null,seconds:90}],'a','b'),[0,0]);
assert.throws(()=>assertSeriesResult({bestOf:1,allowDraw:true},[{winner:null,seconds:90}],'a','b',true));
assert.deepEqual(assertSeriesResult({bestOf:1},games(['a']),'a','b'),[1,0]);assert.deepEqual(assertSeriesResult({bestOf:3},games(['b','b']),'a','b'),[0,2]);assert.deepEqual(assertSeriesResult({bestOf:3},games(['a','b','a']),'a','b'),[2,1]);assert.deepEqual(assertSeriesResult({bestOf:5},games(['a','b','a','b','b']),'a','b'),[2,3]);assert.throws(()=>assertSeriesResult({bestOf:3},games(['a']),'a','b'));assert.throws(()=>assertSeriesResult({bestOf:3},games(['a','a','b']),'a','b'));assert.throws(()=>assertSeriesResult({bestOf:5},games(['a','b','a','a','b']),'a','b'));assert(seriesComplete({bestOf:5},[3,0],3));assert(!seriesComplete({bestOf:5},[2,2],4));assert.deepEqual(assertSeriesResult({legs:4},games(['a','a','a','b']),'a','b'),[3,1]);
const roster=Array.from({length:4},(_,i)=>({id:'00000000-0000-4000-9000-'+String(i+1).padStart(12,'0'),name:'Series '+i,traits:{race:'Human',weapon:'Longbow',power:'No power'},summary:{stats:[80,60,90,50,20],total:300,tier:'E',rank:'Common'}}));
const win=(t,who)=>{const m=nextMatch(t),id=who||m.a;recordMatch(t,m,games(Array(Math.floor((m.bestOf||m.legs)/2)+1).fill(id)));return m;};
for(const type of ['single','double']){const t=createTournament(type,roster,[defaultStage(type)],1,{shuffle:false});let reset=false;while(!t.done){const m=nextMatch(t);assert(m);if(m.label.startsWith('Grand final')){assert.equal(m.bestOf,5);assert.equal(m.legs,undefined);if(type==='double'&&!reset){const loserSide=[m.a,m.b].find(id=>t.runtime.table[id].losses===1);win(t,loserSide);reset=true;}else win(t);}else{assert.equal(m.bestOf,1);win(t);}}const finals=t.history.filter(m=>m.label.startsWith('Grand final'));assert.equal(finals.length,type==='double'?2:1);assert(finals.every(m=>m.results.length===3));}
for(const type of ['swiss','groups']){for(const bestOf of [1,3,5]){const t=createTournament(type,roster,[{...defaultStage(type),bestOf,rounds:2,groups:1}],3);while(!t.done){const m=nextMatch(t);assert.equal(m.bestOf,m.label.startsWith('Grand final')?5:bestOf);win(t);}assert(t.history.filter(m=>!m.bye).every(m=>m.results.length===Math.floor(m.bestOf/2)+1&&m.winner));}}
const old=createTournament('legacy',roster.slice(0,2),[{...defaultStage('single'),bestOf:undefined,legs:1}],9);old.runtime.pending[0].bestOf=undefined;old.runtime.pending[0].legs=1;old.runtime.pending[0].label='Round 1';assert.equal(nextMatch(old).bestOf,5);win(old);const oldHistory=JSON.stringify(old.history);nextMatch(old);assert.equal(JSON.stringify(old.history),oldHistory);
const db=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+f,'utf8'));const env={DB:{prepare(sql){let args=[];return {bind(...values){args=values;return this;},first:async()=>db.prepare(sql).get(...args)||null,all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>({meta:{changes:Number(db.prepare(sql).run(...args).changes)}})};},async batch(statements){const out=[];for(const s of statements)out.push(await s.run());return out;}}};
const request=(path,body)=>worker.fetch(new Request('https://fateforge.test/api/'+path,{method:body?'PUT':'GET',headers:{'oai-authenticated-user-id':'series-owner','content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env);
const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync('public/data.js','utf8')+';this.pools=WHEEL_DATA',ctx);for(const c of roster)assert.equal((await request('characters/'+c.id,{name:c.name,state:{version:1,traits:{race:'Human',weapon:'Longbow'},pools:ctx.pools}})).status,200);
const stored=(await(await request('characters')).json()).characters;roster.splice(0,roster.length,...stored);
const t=createTournament('Bo3 save',roster,[{...defaultStage('swiss'),bestOf:3,rounds:1}],10),id=crypto.randomUUID();let m=nextMatch(t);win(t);{const r=await request('tournaments/'+id,{name:t.name,state:t});assert.equal(r.status,200,JSON.stringify(await r.json()));}const broken=structuredClone(t);broken.history[0].results.push({winner:m.a,seconds:1});broken.history[0].score[0]++;assert.equal((await request('tournaments/'+id,{name:t.name,state:broken})).status,400);while(!t.done)win(t);assert.equal((await request('tournaments/'+id,{name:t.name,state:t})).status,200);const saved=(await(await request('tournaments/'+id)).json()).tournament.state;assert.deepEqual(saved,t);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM match_records').get().n,t.history.filter(m=>!m.bye).length);
for(const bestOf of [1,3,5]){const quick=createTournament('sim',roster,[{...defaultStage('swiss'),rounds:1,bestOf}],40);while(!quick.done){const result=resolveMatch(quick);assert(result.results.length>=Math.floor(result.bestOf/2)+1&&result.results.length<=result.bestOf);assert.equal(Math.max(...result.score),Math.floor(result.bestOf/2)+1);}}
const html=await(await worker.fetch(new Request('https://fateforge.test/arena'),env)).text();assert(html.includes('id="duel-best-of"'));assert(!/\blegs\b/i.test(html));assert.equal((await worker.fetch(new Request('https://fateforge.test/series.js'),env)).status,200);
console.log('Series passed: Bo1/3/5 early finish, deciding games, no post-clinch games, groups and Swiss, single final, double final and reset forced Bo5, legacy recordings and pending finals, saved-series validation, one W/L per series, and quick simulations.');
