import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import worker from '../dist/server/index.js';
import {LEAGUES} from '../public/leagues.js';
import {resolveConditions} from '../public/conditions.js';
import {simulateLeagueSeries} from '../public/league-sim-worker.js';
import {summarizeChampionHistory} from '../public/champion-history.js';
import initSqlJs from 'sql.js';import {indexedDB} from 'fake-indexeddb';import {createStorage} from '../_site/sqlite-store.js';import pagesWorker from '../_site/local-api.js';import migrations from '../_site/local-schema.js';
const fixture=Array.from({length:140},(_,i)=>({id:crypto.randomUUID(),name:'Fighter '+i,summary:{tier:'C',wheelRarity:'common',stats:[100,150,150,100,150],total:650},traits:{weapon:'Longbow',power:'Fire manipulation',power2:'No second power',weakness:'None'}}));
for(const legs of [1,2]){const weeks=LEAGUES.schedule(fixture.slice(0,20).map(c=>c.id),legs),pairs=new Map();assert.equal(weeks.length,19*legs);for(const week of weeks){assert.equal(new Set(week.flat()).size,20);for(const [a,b]of week){const key=[a,b].sort().join(':');pairs.set(key,(pairs.get(key)||0)+1);}}assert.equal(pairs.size,190);assert([...pairs.values()].every(n=>n===legs));}
const fake=m=>Array.from({length:Math.floor(m.bestOf/2)+1},(_,i)=>({winner:m.a,seconds:1,combatVersion:9,environment:resolveConditions((m.seed+i*65537)>>>0,m.conditions)}));
for(const roundRobin of [1,2])for(const bestOf of [1,3,5]){
 const w=LEAGUES.create(crypto.randomUUID(),fixture,17,{roundRobin,bestOf});let count=0,previousWeek=0;
 while(LEAGUES.next(w)){const m=LEAGUES.next(w);if(m.phase==='league'){assert(m.week>=previousWeek);previousWeek=m.week;assert.equal(m.division,count%7);}if(m.phase!=='league'&&w.cup.players.length===2)assert.equal(m.bestOf,5);LEAGUES.record(w,m.id,fake(m));count++;}
 assert.equal(count,1330*roundRobin+7*19+15);assert.equal(w.cupResults.length,8);for(const c of w.cupResults.slice(0,7)){assert.equal(c.byes.length,12);assert.equal(c.entrants.length,20);assert.equal(new Set(c.entrants).size,20);}assert.equal(new Set(w.qualifiers.map(c=>c.id)).size,16);
 const replacements=['legendary','legendary','unique','unique','mythic'].map((r,i)=>({...fixture[i],id:crypto.randomUUID(),summary:{...fixture[i].summary,wheelRarity:r}})),{archive,world}=LEAGUES.rollover(w,replacements);LEAGUES.sizes(world);assert.equal(world.season,2);assert.equal(archive.retired.length,5);assert.equal(archive.movement.length,36);for(const m of archive.movement)assert(world.divisions[m.to].includes(m.id));for(const c of archive.retired)assert(!world.roster.some(r=>r.id===c.id));assert(world.divisions[6].slice().filter(id=>replacements.some(r=>r.id===id)).length===5);assert.throws(()=>LEAGUES.rollover(world,replacements));
}
console.log('Schedule/rules passed: both season lengths × Bo1/3/5, week ordering, proper 20-member byes, Bo5 finals, 16 distinct qualifiers, simultaneous 36 movements and exact retirement/replacement rarities.');
const titleHistory=['league:0','league-cup:0','interleague'].flatMap((key,k)=>[1,2,3].map(season=>({divisionKey:key,label:key,characterId:season===3?'new-winner':'repeat-winner',characterName:'Winner',tournamentId:key+season,tournamentName:'Season '+season,completedAt:season*100+k})));const titleStats=summarizeChampionHistory(titleHistory).records;for(const key of ['league:0','league-cup:0','interleague']){const repeat=titleStats.find(r=>r.characterId==='repeat-winner'&&r.divisionKey===key),current=titleStats.find(r=>r.characterId==='new-winner'&&r.divisionKey===key);assert.equal(repeat.titles,2);assert.equal(repeat.bestStreak,2);assert.equal(repeat.currentStreak,0);assert.equal(current.currentStreak,1);}
const db=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const env={DB:{prepare(sql){let args=[];return {bind(...v){args=v;return this;},first:async()=>db.prepare(sql).get(...args)||null,all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>({meta:{changes:Number(db.prepare(sql).run(...args).changes)}})};},async batch(statements){db.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}}};
const call=async(path='/api/leagues',body,method=body?'POST':'GET')=>{const r=await worker.fetch(new Request('https://fateforge.test'+path,{method,headers:{'oai-authenticated-user-id':'local','content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env);return {status:r.status,...await r.json()};};
const ok=r=>assert.equal(r.status,200,r.error);
assert.equal((await call()).world,null);assert.equal(db.prepare('SELECT COUNT(*) n FROM saved_characters').get().n,0);
const ids=Array.from({length:2},()=>crypto.randomUUID());ok(await call('/api/characters/bulk-generate',{ids}));const preserved=(await call('/api/characters/'+ids[0])).character;
let command={action:'start',worldId:crypto.randomUUID(),revision:0,operationId:crypto.randomUUID(),settings:{roundRobin:1,bestOf:1}},response=await call('/api/leagues',command);ok(response);let {world,revision}=response;assert.equal(world.roster.length,140);ok(await call('/api/leagues',command));assert.equal(db.prepare('SELECT COUNT(*) n FROM saved_characters').get().n,142);
assert.equal((await call('/api/characters/'+world.roster[0].id,undefined,'DELETE')).status,409);assert.equal((await call('/api/characters/bulk-remove',{ids:[ids[0],world.roster[0].id]})).status,409);assert((await call('/api/characters/'+ids[0])).character);
assert.equal((await call('/api/leagues',{...command,operationId:crypto.randomUUID()})).status,409);
assert.equal((await call('/api/characters/'+world.roster[0].id)).character.state.pools.base.race.length>50,true);
assert.equal(db.prepare('SELECT COUNT(*) n FROM character_pools').get().n,1);
const m=LEAGUES.next(world),actual=simulateLeagueSeries({match:m,a:world.roster.find(c=>c.id===m.a),b:world.roster.find(c=>c.id===m.b)});assert.deepEqual(actual,simulateLeagueSeries({match:m,a:world.roster.find(c=>c.id===m.a),b:world.roster.find(c=>c.id===m.b)}));
assert.equal((await call('/api/leagues',{action:'record',operationId:crypto.randomUUID(),revision,matchId:m.id,results:[{winner:'invalid',seconds:1}]})).status,400);
let n=0;
while(LEAGUES.next(world)){const next=LEAGUES.next(world);command={action:'record',operationId:crypto.randomUUID(),revision,matchId:next.id,results:n===0?actual:fake(next)};response=await call('/api/leagues',command);ok(response);({world,revision}=response);if(n===0){ok(await call('/api/leagues',command));assert.equal((await call('/api/leagues',{...command,results:fake(next)})).status,409);}n++;if(n%350===0)console.log('Persistence season:',n,'series saved');}
assert.equal(n,1478);assert.equal(db.prepare('SELECT COUNT(*) n FROM match_records').get().n,1478);assert.equal(db.prepare('SELECT COUNT(*) n FROM champion_history').get().n,15);assert.equal(db.prepare('SELECT COUNT(*) n FROM current_champions').get().n,15);
const before=(await call('/api/characters')).characters;assert.equal(before.reduce((sum,c)=>sum+c.matchRecord.matches,0),1478*2);assert.equal(before.reduce((sum,c)=>sum+c.championships,0),15);
command={action:'rollover',operationId:crypto.randomUUID(),revision};response=await call('/api/leagues',command);ok(response);ok(await call('/api/leagues',command));({world,revision}=response);LEAGUES.sizes(world);assert.equal(world.season,2);assert.equal(db.prepare('SELECT COUNT(*) n FROM saved_characters').get().n,142);assert.equal(db.prepare('SELECT COUNT(*) n FROM league_members').get().n,140);assert.equal(db.prepare('SELECT COUNT(*) n FROM league_seasons').get().n,1);
const archive=(await call('/api/leagues/history/1')).archive;assert.equal(archive.history.length,1478);assert.deepEqual(archive.replacements.map(c=>c.summary.wheelRarity).sort(),['legendary','legendary','mythic','unique','unique']);for(const retired of archive.retired)assert.equal((await call('/api/characters/'+retired.id)).status,404);
assert.deepEqual((await call('/api/characters/'+ids[0])).character,preserved);
// Exercise competing commands claiming the same revision before either commits.
const next=LEAGUES.next(world),base={action:'record',revision,matchId:next.id,results:fake(next)},rivals=await Promise.all([call('/api/leagues',{...base,operationId:crypto.randomUUID()}),call('/api/leagues',{...base,operationId:crypto.randomUUID()})]);assert.deepEqual(rivals.map(r=>r.status).sort(),[200,409]);assert.equal(db.prepare('SELECT COUNT(*) n FROM match_records').get().n,1479);
// Import this fully completed, rolled-over season through the real Pages backup bridge.
const SQL=await initSqlJs(),backupDb=new SQL.Database();for(const m of migrations)backupDb.run(m);for(const {name}of db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all()){const rows=db.prepare('SELECT * FROM '+name).all();for(const row of rows){const columns=Object.keys(row);backupDb.run(`INSERT INTO ${name}(${columns.join(',')}) VALUES(${columns.map(()=>'?').join(',')})`,Object.values(row));}}backupDb.run('PRAGMA user_version=13');backupDb.run('PRAGMA application_id=1178686533');
const pages=createStorage({SQL,migrations,worker:pagesWorker,indexedDB,databaseName:'full-season-restore'});await pages.importBackup(backupDb.export());const archivedResponse=await pages.fetch('/api/leagues/history/1'),restoredArchive=(await archivedResponse.json()).archive;assert.deepEqual(restoredArchive,archive);const reopened=createStorage({SQL,migrations,worker:pagesWorker,indexedDB,databaseName:'full-season-restore'});assert.deepEqual((await(await reopened.fetch('/api/leagues')).json()).world,(await call()).world);assert.equal((await(await reopened.fetch('/api/champions')).json()).history.length,15);backupDb.close();
console.log('League persistence passed: optional start, generated/shared catalogs, protected deletion, actual deterministic combat, full season/cups, exactly-once W/L and 15 category awards, retry-safe archive/rollover, retirement history, preserved unrelated fighters and conflicting command rejection.');
