import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import worker from '../dist/server/index.js';
import {LEAGUES} from '../public/leagues.js';
import {resolveConditions} from '../public/conditions.js';
import {simulateLeagueSeries} from '../public/league-sim-worker.js';
import {summarizeChampionHistory} from '../public/champion-history.js';
import initSqlJs from 'sql.js';import {indexedDB} from 'fake-indexeddb';import {createStorage} from '../_site/sqlite-store.js';import pagesWorker from '../_site/local-api.js';import migrations from '../_site/local-schema.js';
const fixture=Array.from({length:164},(_,i)=>({id:crypto.randomUUID(),name:'Fighter '+i,summary:{tier:'C',wheelRarity:'common',stats:[100,150,150,100,150],total:650},traits:{weapon:'Longbow',power:'Fire manipulation',power2:'No second power',weakness:'None'}}));
for(const size of [20,24])for(const legs of [1,2]){const weeks=LEAGUES.schedule(fixture.slice(0,size).map(c=>c.id),legs),pairs=new Map();assert.equal(weeks.length,(size-1)*legs);for(const week of weeks){assert.equal(new Set(week.flat()).size,size);for(const [a,b]of week){const key=[a,b].sort().join(':');pairs.set(key,(pairs.get(key)||0)+1);}}assert.equal(pairs.size,size*(size-1)/2);assert([...pairs.values()].every(n=>n===legs));}
const fake=m=>Array.from({length:Math.floor(m.bestOf/2)+1},(_,i)=>({winner:m.a,seconds:1,combatVersion:13,environment:resolveConditions((m.seed+i*65537)>>>0,m.conditions)}));
const drawn=LEAGUES.create(crypto.randomUUID(),fixture,99),drawMatch=LEAGUES.next(drawn);LEAGUES.record(drawn,drawMatch.id,[{winner:null,seconds:90,combatVersion:13,environment:resolveConditions(drawMatch.seed,drawMatch.conditions)}]);for(const id of [drawMatch.a,drawMatch.b]){const row=LEAGUES.standings(drawn,drawMatch.division).find(r=>r.id===id);assert.equal(row.points,1);assert.equal(row.draws,1);assert.equal(row.losses,0);}
for(const roundRobin of [1,2])for(const bestOf of [1,3,5]){
 const w=LEAGUES.create(crypto.randomUUID(),fixture,17,{roundRobin,bestOf});let count=0,previousWeek=0;
 const weeks=w.divisions.map(ids=>LEAGUES.schedule(ids,roundRobin)),ordered=Array.from({length:LEAGUES.weekCount(w)},(_,week)=>weeks.flatMap((schedule,division)=>(schedule[week]||[]).map(([a,b],slot)=>({a,b,slot,division}))).sort((a,b)=>a.slot-b.slot||a.division-b.division));
 while(LEAGUES.next(w)){const m=LEAGUES.next(w);if(m.phase==='league'){assert(m.week>=previousWeek);previousWeek=m.week;const position=w.history.filter(x=>x.phase==='league'&&x.week===m.week).length,expected=ordered[m.week-1][position];assert.deepEqual([m.a,m.b,m.division],[expected.a,expected.b,expected.division]);}if(m.phase!=='league'&&!m.phase.endsWith('-qualifier')&&w.cup.players.length===2)assert.equal(m.bestOf,5);LEAGUES.record(w,m.id,fake(m));count++;}
 assert.equal(count,1846*roundRobin+239);assert.equal(w.cupResults.length,9);for(const c of w.cupResults.slice(0,7)){const size=LEAGUES.divisionSizes[c.division];assert.equal(c.byes.length,32-size);assert.equal(c.entrants.length,size);assert.equal(new Set(c.entrants).size,size);}assert.equal(w.qualificationResults.length,2);assert.equal(w.qualificationResults[0].qualified.length,2);assert.equal(w.qualificationResults[0].eliminated.length,12);assert.equal(w.qualificationResults[1].qualified.length,4);assert.equal(w.europaQualifiers.length,16);assert(w.europaQualifiers.every(c=>!w.qualifiers.some(q=>q.id===c.id)));assert(w.history.filter(m=>m.phase.endsWith('-qualifier')).every(m=>m.bestOf===3));assert.equal(new Set(w.qualifiers.map(c=>c.id)).size,16);
 const replacements=LEAGUES.recruitIntake(w).map((r,i)=>({...fixture[i],id:crypto.randomUUID(),summary:{...fixture[i].summary,wheelRarity:r??'common'}})),{archive,world}=LEAGUES.rollover(w,replacements);LEAGUES.sizes(world);assert.equal(world.season,2);assert.equal(archive.retired.length,3);assert.equal(archive.movement.length,36);for(const m of archive.movement)assert(world.divisions[m.to].includes(m.id));for(const c of archive.retired)assert(!world.roster.some(r=>r.id===c.id));assert(world.divisions[6].slice().filter(id=>replacements.some(r=>r.id===id)).length===3);assert.throws(()=>LEAGUES.rollover(world,replacements));
}
console.log('Schedule/rules passed: both season lengths × Bo1/3/5, week ordering, proper 20/24-member byes, Bo5 finals, 16 distinct qualifiers, simultaneous 36 movements and exact retirement/replacement rarities.');
const legacyWorld=LEAGUES.create(crypto.randomUUID(),fixture,55,{roundRobin:1});legacyWorld.version=1;legacyWorld.roster=fixture.slice(0,140);legacyWorld.divisions=Array.from({length:7},(_,d)=>legacyWorld.roster.slice(d*20,d*20+20).map(c=>c.id));LEAGUES.sizes(legacyWorld);while(LEAGUES.next(legacyWorld)){const m=LEAGUES.next(legacyWorld);LEAGUES.record(legacyWorld,m.id,fake(m));}assert.equal(legacyWorld.history.length,1478);const legacyReplacements=LEAGUES.recruitIntake(legacyWorld).map((rarity,i)=>({...fixture[i],id:crypto.randomUUID(),summary:{...fixture[i].summary,wheelRarity:rarity??'common'}})),expanded=LEAGUES.rollover(legacyWorld,legacyReplacements,fixture.slice(140));LEAGUES.sizes(expanded.world);assert.deepEqual(expanded.world.divisions.map(d=>d.length),[20,24,24,24,24,24,24]);assert.equal(expanded.archive.expansion.length,24);
const titleHistory=['league:0','league-cup:0','interleague'].flatMap((key,k)=>[1,2,3].map(season=>({divisionKey:key,label:key,characterId:season===3?'new-winner':'repeat-winner',characterName:'Winner',tournamentId:key+season,tournamentName:'Season '+season,completedAt:season*100+k})));const titleStats=summarizeChampionHistory(titleHistory).records;for(const key of ['league:0','league-cup:0','interleague']){const repeat=titleStats.find(r=>r.characterId==='repeat-winner'&&r.divisionKey===key),current=titleStats.find(r=>r.characterId==='new-winner'&&r.divisionKey===key);assert.equal(repeat.titles,2);assert.equal(repeat.bestStreak,2);assert.equal(repeat.currentStreak,0);assert.equal(current.currentStreak,1);}
const db=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const env={DB:{prepare(sql){let args=[];return {bind(...v){args=v;return this;},first:async()=>db.prepare(sql).get(...args)||null,all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>({meta:{changes:Number(db.prepare(sql).run(...args).changes)}})};},async batch(statements){db.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}}};
const call=async(path='/api/leagues',body,method=body?'POST':'GET')=>{const r=await worker.fetch(new Request('https://fateforge.test'+path,{method,headers:{'oai-authenticated-user-id':'local','content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env);return {status:r.status,...await r.json()};};
const ok=r=>assert.equal(r.status,200,r.error);
assert.equal((await call()).world,null);assert.equal(db.prepare('SELECT COUNT(*) n FROM saved_characters').get().n,0);
const ids=Array.from({length:2},()=>crypto.randomUUID());ok(await call('/api/characters/bulk-generate',{ids}));const preserved=(await call('/api/characters/'+ids[0])).character;
let command={action:'start',worldId:crypto.randomUUID(),revision:0,operationId:crypto.randomUUID(),settings:{roundRobin:1,bestOf:1}},response=await call('/api/leagues',command);ok(response);let {world,revision}=response;assert.equal(world.roster.length,164);ok(await call('/api/leagues',command));assert.equal(db.prepare('SELECT COUNT(*) n FROM saved_characters').get().n,166);
assert.equal((await call('/api/characters/'+world.roster[0].id,undefined,'DELETE')).status,409);assert.equal((await call('/api/characters/bulk-remove',{ids:[ids[0],world.roster[0].id]})).status,409);assert((await call('/api/characters/'+ids[0])).character);
assert.equal((await call('/api/leagues',{...command,operationId:crypto.randomUUID()})).status,409);
assert.equal((await call('/api/characters/'+world.roster[0].id)).character.state.pools.base.race.length>50,true);
assert.equal(db.prepare('SELECT COUNT(*) n FROM character_pools').get().n,1);
const m=LEAGUES.next(world),actual=simulateLeagueSeries({match:m,a:world.roster.find(c=>c.id===m.a),b:world.roster.find(c=>c.id===m.b)});assert.deepEqual(actual,simulateLeagueSeries({match:m,a:world.roster.find(c=>c.id===m.a),b:world.roster.find(c=>c.id===m.b)}));
assert.equal((await call('/api/leagues',{action:'record',operationId:crypto.randomUUID(),revision,matchId:m.id,results:[{winner:'invalid',seconds:1}]})).status,400);
let n=0;
while(LEAGUES.next(world)){
 if(n===0){const next=LEAGUES.next(world);command={action:'record',operationId:crypto.randomUUID(),revision,matchId:next.id,results:actual};response=await call('/api/leagues',command);ok(response);({world,revision}=response);ok(await call('/api/leagues',command));assert.equal((await call('/api/leagues',{...command,results:fake(next)})).status,409);n++;continue;}
 const phase=world.phase,preview=structuredClone(world),series=[];
 while(preview.phase===phase&&LEAGUES.next(preview)){const next=LEAGUES.next(preview),record={matchId:next.id,results:fake(next)};series.push(record);LEAGUES.record(preview,record.matchId,record.results);}
 command={action:'recordBatch',operationId:crypto.randomUUID(),revision,series,compact:true};response=await call('/api/leagues',command);ok(response);assert(!Object.hasOwn(response,'world'));ok(await call('/api/leagues',command));assert.deepEqual((await call()).world,preview);world=preview;revision=response.revision;n+=series.length;
 if(series.length>1000)assert(db.prepare('SELECT request_json FROM league_operations WHERE operation_id = ?').get(command.operationId).request_json.startsWith('sha256:'));
 console.log('Persistence phase:',phase,series.length,'series in one checkpoint');
}
assert.equal(n,2085);assert.equal(db.prepare('SELECT COUNT(*) n FROM match_records').get().n,2085);assert.equal(db.prepare('SELECT COUNT(*) n FROM champion_history').get().n,16);assert.equal(db.prepare('SELECT COUNT(*) n FROM current_champions').get().n,16);
const before=(await call('/api/characters')).characters;assert.equal(before.reduce((sum,c)=>sum+c.matchRecord.matches,0),2085*2);assert.equal(before.reduce((sum,c)=>sum+c.championships,0),16);
command={action:'rollover',operationId:crypto.randomUUID(),revision};response=await call('/api/leagues',command);ok(response);ok(await call('/api/leagues',command));({world,revision}=response);LEAGUES.sizes(world);assert.equal(world.season,2);assert.equal(db.prepare('SELECT COUNT(*) n FROM saved_characters').get().n,164);assert.equal(db.prepare('SELECT COUNT(*) n FROM league_members').get().n,164);assert.equal(db.prepare('SELECT COUNT(*) n FROM league_seasons').get().n,1);
const archive=(await call('/api/leagues/history/1')).archive;assert.equal(archive.history.length,2085);assert.deepEqual(new Set(archive.playerRecruits),new Set(ids));assert(ids.every(id=>world.divisions[6].includes(id)));assert.equal(archive.replacements.length,3);assert.equal(archive.careerRulesVersion,2);for(const retired of archive.retired)assert.equal((await call('/api/characters/'+retired.id)).status,404);
const admitted=(await call('/api/characters/'+ids[0])).character;assert.deepEqual(admitted.state,preserved.state);assert.deepEqual(admitted.summary.stats,preserved.summary.stats);assert.equal(admitted.name,preserved.name);assert.equal(admitted.createdAt,preserved.createdAt);assert.equal(admitted.leagueMember.division,6);assert.equal(admitted.summary.leagueDebut.season,2);
// Exercise competing commands claiming the same revision before either commits.
const next=LEAGUES.next(world),base={action:'record',revision,matchId:next.id,results:fake(next)},rivals=await Promise.all([call('/api/leagues',{...base,operationId:crypto.randomUUID()}),call('/api/leagues',{...base,operationId:crypto.randomUUID()})]);assert.deepEqual(rivals.map(r=>r.status).sort(),[200,409]);assert.equal(db.prepare('SELECT COUNT(*) n FROM match_records').get().n,2086);
// Import this fully completed, rolled-over season through the real Pages backup bridge.
const batchBefore=await call(),batchMatches=LEAGUES.upcoming(batchBefore.world,12),batchPreview=structuredClone(batchBefore.world),batchSeries=batchMatches.map(match=>({matchId:match.id,results:fake(match)}));for(const match of batchSeries)LEAGUES.record(batchPreview,match.matchId,match.results);const batchCommand={action:'recordBatch',compact:true,revision:batchBefore.revision,operationId:crypto.randomUUID(),series:batchSeries},batched=await call('/api/leagues',batchCommand);ok(batched);assert(!Object.hasOwn(batched,'world'));ok(await call('/api/leagues',batchCommand));assert.deepEqual((await call()).world,batchPreview);assert.equal(db.prepare('SELECT COUNT(*) n FROM match_records').get().n,2086+12);
const SQL=await initSqlJs(),backupDb=new SQL.Database();for(const m of migrations)backupDb.run(m);for(const {name}of db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all()){const rows=db.prepare('SELECT * FROM '+name).all();for(const row of rows){const columns=Object.keys(row);backupDb.run(`INSERT INTO ${name}(${columns.join(',')}) VALUES(${columns.map(()=>'?').join(',')})`,Object.values(row));}}backupDb.run('PRAGMA user_version='+migrations.length);backupDb.run('PRAGMA application_id=1178686533');
const pages=createStorage({SQL,migrations,worker:pagesWorker,indexedDB,databaseName:'full-season-restore'});await pages.importBackup(backupDb.export());const archivedResponse=await pages.fetch('/api/leagues/history/1'),restoredArchive=(await archivedResponse.json()).archive;assert.deepEqual(restoredArchive,archive);const reopened=createStorage({SQL,migrations,worker:pagesWorker,indexedDB,databaseName:'full-season-restore'});assert.deepEqual((await(await reopened.fetch('/api/leagues')).json()).world,(await call()).world);assert.equal((await(await reopened.fetch('/api/champions')).json()).history.length,16);backupDb.close();
console.log('League persistence passed: optional start, generated/shared catalogs, protected deletion, actual deterministic combat, full season/cups, exactly-once W/L and 16 category awards, retry-safe archive/rollover, retirement history, preserved unrelated fighters and conflicting command rejection.');
// A fresh world preserves the old world and avoids ambiguous Season 1 lookups.
const active=await call();assert.equal((await call('/api/leagues',{action:'freshStart',revision:active.revision,operationId:crypto.randomUUID(),worldId:crypto.randomUUID(),settings:active.world.settings})).status,400);
const finished=structuredClone(active.world);finished.phase='complete';finished.cup=null;db.prepare('UPDATE league_worlds SET state_json=? WHERE owner_id=?').run(JSON.stringify(finished),'local');
assert.equal((await call('/api/leagues',{action:'freshStart',revision:active.revision,operationId:crypto.randomUUID(),worldId:finished.id,settings:finished.settings})).status,400);assert.equal((await call()).revision,active.revision);
const formerFighter=finished.roster[0].id,freshCommand={action:'freshStart',operationId:crypto.randomUUID(),revision:active.revision,worldId:crypto.randomUUID(),settings:finished.settings},fresh=await call('/api/leagues',freshCommand);ok(fresh);ok(await call('/api/leagues',freshCommand));assert.equal(fresh.world.id,freshCommand.worldId);assert.equal(fresh.world.season,1);assert.equal(fresh.world.engineVersion,13);assert.equal(fresh.world.generationVersion,4);assert(fresh.world.careerEnabled);assert(fresh.world.roster.every(c=>c.summary.generationVersion===4));assert((await call('/api/characters/'+formerFighter)).character);assert.equal(db.prepare('SELECT id FROM league_worlds').get().id,freshCommand.worldId);assert.equal(db.prepare('SELECT COUNT(*) n FROM league_members').get().n,164);assert.equal((await call('/api/leagues/history/2?worldId='+finished.id)).archive.closedWorld,true);assert.deepEqual((await call('/api/leagues/history/1?worldId='+archive.id)).archive,archive);assert.equal(db.prepare('SELECT COUNT(*) n FROM champion_history').get().n,16);
// Closing an unplayed fresh world is allowed, and keeps its full snapshot.
const another=await call('/api/leagues',{...freshCommand,operationId:crypto.randomUUID(),revision:fresh.revision,worldId:crypto.randomUUID()});ok(another);const preservedFresh=(await call('/api/leagues/history/1?worldId='+fresh.world.id)).archive;assert.equal(preservedFresh.history.length,0);assert.equal(preservedFresh.roster.length,164);assert.deepEqual((await call('/api/leagues/history/1?worldId='+archive.id)).archive,archive);
assert.equal((await call('/api/leagues',{...freshCommand,operationId:crypto.randomUUID(),revision:another.revision,worldId:archive.id})).status,400);assert.equal((await call()).revision,another.revision);
console.log('Fresh worlds passed: retry-safe generation, distinct world IDs, preserved active fighters/titles/archives, world-specific same-number seasons, unplayed-world closure and pinned generation/career settings.');
