// Offline, seeded review. Writes aggregate evidence, never touches a live save.
import fs from 'node:fs';
import vm from 'node:vm';
import {availableParallelism} from 'node:os';
import {createHash} from 'node:crypto';
import {Worker,isMainThread,parentPort,workerData} from 'node:worker_threads';
import {simulate,combatStyle,tierFor} from '../public/combat-v10.js';
import {simulate as simulate9} from '../public/combat-v9.js';
import {LEAGUES} from '../public/leagues.js';
import {simulateLeagueSeries} from '../public/league-sim-worker.js';
import {drawAtTimeLimit} from '../public/series.js';
const mode=workerData?.mode??process.argv[2]??'weapons';
const engineFiles=['combat-v10.js','combat-v10-profile.js','combat-v10-contact.js','combat-v10-environment.js','combat-v10-powers.js','abilities.js','conditions.js'];
const engineFingerprint=createHash('sha256').update(engineFiles.map(file=>fs.readFileSync(new URL('../public/'+file,import.meta.url),'utf8').replaceAll('\r\n','\n')).join('\n')).digest('hex');
const environments=[];for(const time of ['dawn','day','dusk','night'])for(const weather of ['clear','rain','frost','storm'])for(const ground of ['stone','water'])environments.push({time,weather,ground});
const fighter=(id,stats,weapon,power='No power')=>({id,name:id,summary:{stats,total:stats.reduce((a,b)=>a+b,0)},traits:{weapon,power,power2:'No second power',weakness:'None'}});
function generator(seed){const c={crypto};vm.createContext(c);for(const [file,name]of [['luck','WHEEL_LUCK'],['data','WHEEL_DATA']])vm.runInContext(fs.readFileSync(new URL('../public/'+file+'-v2.js',import.meta.url),'utf8')+';this.'+file+'='+name,c);const random=LEAGUES.rng(seed);let serial=0;return rarity=>{const roll=c.luck.rollTraits(c.data,n=>Math.floor(random()*n),rarity),stats=[0,0,0,0,0];for(const [slot,name]of Object.entries(roll.traits)){if(/^no (second )?power$/i.test(name))continue;const list=slot==='subrace'?c.data.subrace[roll.traits.race]:slot==='subclass'?c.data.subclass[roll.traits.class]:c.data.base[slot];list.find(o=>o.name===name).stats.forEach((n,i)=>stats[i]+=n);}const clamped=stats.map(n=>Math.max(0,n)),total=clamped.reduce((a,b)=>a+b,0);return {id:`${seed}-${++serial}`,name:`Fighter ${serial}`,traits:roll.traits,summary:{stats:clamped,total,tier:tierFor(total),wheelRarity:roll.wheelRarity,generationVersion:roll.generationVersion}};};}
const describe=roster=>({fighters:roster.length,Aplus:roster.filter(c=>c.summary.total>=1500).length/roster.length,Splus:roster.filter(c=>c.summary.total>=2100).length/roster.length,SS:roster.filter(c=>c.summary.total>=3000).length/roster.length,mean:roster.reduce((n,c)=>n+c.summary.total,0)/roster.length,twoPowers:roster.filter(c=>![c.traits.power,c.traits.power2].some(p=>/^no (second )?power$/i.test(p))).length/roster.length,arcane:roster.filter(c=>combatStyle(c)==='arcane').length/roster.length});
function aggregate(rows,keys){const groups=new Map();for(const r of rows){const key=keys.map(k=>r[k]).join('|');let g=groups.get(key);if(!g)groups.set(key,g={...Object.fromEntries(keys.map(k=>[k,r[k]])),fights:0,score:0,draws:0,seconds:0});g.fights++;g.score+=r.score;g.draws+=r.draw?1:0;g.seconds+=r.seconds;}return [...groups.values()].map(g=>({...g,score:g.score/g.fights,draws:g.draws/g.fights,seconds:g.seconds/g.fights}));}
function output(data){fs.mkdirSync('validation/balance-v10',{recursive:true});fs.writeFileSync('validation/balance-v10/'+mode+'.json',JSON.stringify({combatVersion:10,engineFingerprint,generationVersion:2,seed:20264005,...data},null,2)+'\n');}
if(!isMainThread){
 if(mode==='worlds'){
  for(const index of workerData.indices){const seed=20264005+index*7919,generate=generator(seed);let w=LEAGUES.create('review-world-'+index,Array.from({length:164},()=>generate()),seed,{roundRobin:1,bestOf:1});w.engineVersion=10;w.careerRulesVersion=1;const seasons=[],allTimes=[],styleTitles={melee:0,arcane:0,ranged:0},styleEntrants={melee:0,arcane:0,ranged:0};let draws=0,leagueGames=0,firstWins=0,decisive=0;
   for(let season=1;season<=30;season++){
    const characters=new Map(w.roster.map(c=>[c.id,c]));while(LEAGUES.next(w)){const m=LEAGUES.next(w),results=simulateLeagueSeries({match:m,a:characters.get(m.a),b:characters.get(m.b)});for(const r of results){allTimes.push(r.seconds);if(r.winner){decisive++;firstWins+=r.winner===m.a?1:0;}if(m.phase==='league'){leagueGames++;draws+=r.winner===null?1:0;}}LEAGUES.record(w,m.id,results);}
    const main=w.cupResults.find(c=>c.competition==='champions');styleTitles[combatStyle(characters.get(main.champion))]++;for(const q of w.qualifiers)styleEntrants[combatStyle(characters.get(q.id))]++;
    const retired=LEAGUES.movement(w);seasons.push({season,...describe(w.roster),careerExits:retired.retired.filter(id=>retired.retirementReasons[id]==='Career completed').length,deferred:retired.deferredCareers.length,oldestDeferred:retired.deferredCareers.length?Math.max(...retired.deferredCareers.map(id=>season-w.careers[id].eligibleSeason)):0});
    const intake=LEAGUES.intake(w.seed^Math.imul(w.season,7919)).map(generate);w=LEAGUES.rollover(w,intake).world;w.engineVersion=10;w.careerRulesVersion=1;LEAGUES.sizes(w);
    if(season%5===0)parentPort.postMessage({progress:`World ${index+1}: season ${season}/30`});
   }
   allTimes.sort((a,b)=>a-b);parentPort.postMessage({world:{index,seasons,styleTitles,styleEntrants,leagueDraws:draws/leagueGames,startingSide:firstWins/decisive,medianSeconds:allTimes[Math.floor(allTimes.length*.5)],p90Seconds:allTimes[Math.floor(allTimes.length*.9)],games:allTimes.length}});
  }
 }else{const rows=[];for(const t of workerData.tasks){const a=t.reverse?t.b:t.a,b=t.reverse?t.a:t.b,result=drawAtTimeLimit((t.legacy?simulate9:simulate)(a,b,t.seed,{conditions:t.environment,headless:true}),true);rows.push({...t,a:undefined,b:undefined,environment:undefined,score:result.winner===null?.5:result.winner===t.a.id?1:0,seconds:result.seconds,draw:result.winner===null,replayMatches:t.expected?JSON.stringify(result)===JSON.stringify(t.expected):undefined,expected:undefined});}parentPort.postMessage({rows});}
}else if(mode==='generation'){
 const context={crypto};vm.createContext(context);for(const [file,name]of [['luck','WHEEL_LUCK'],['data','WHEEL_DATA']])vm.runInContext(fs.readFileSync(new URL('../public/'+file+'-v2.js',import.meta.url),'utf8')+';this.'+file+'='+name,context);
 const samples={};for(const rarity of ['ordinary','common','uncommon','rare','unique','legendary','mythic']){const generate=generator(314159265),n=rarity==='ordinary'?50000:10000,roster=Array.from({length:n},()=>generate(rarity==='ordinary'?undefined:rarity));samples[rarity]=describe(roster);samples[rarity].weaknesses=roster.reduce((r,c)=>(r[c.traits.weakness]=(r[c.traits.weakness]||0)+1,r),{});samples[rarity].topPrimary=Object.fromEntries(['strength','speed','durability','iq','magic'].map(slot=>{const pool=context.data.base[slot],top=[...pool].sort((a,b)=>b.stats.reduce((x,y)=>x+y,0)-a.stats.reduce((x,y)=>x+y,0))[0],weighted=rarity==='ordinary'?null:context.luck.biasOptions(pool,rarity,slot);return [slot,{name:top.name,sampledShare:roster.filter(c=>c.traits[slot]===top.name).length/n,...(weighted?{exactShare:weighted.find(o=>o.name===top.name).weight/weighted.reduce((sum,o)=>sum+o.weight,0)}:{})}];}));console.log(rarity,JSON.stringify(describe(roster)));}output({sampleSeed:314159265,samples});
}else{
 const began=performance.now(),tasks=[];
 if(mode==='weapons'){const weapons=['Staff','Magic wand','Crystal orb','Spellbook','Sword','Longbow','Mace','Shield','Tower shield','Spear','Dagger','Rifle'],profiles={balanced:[300,300,300,300,300],physical:[500,400,400,150,50],magical:[100,250,300,250,600]};for(const [profile,stats]of Object.entries(profiles))for(const weapon of weapons)for(const opponentWeapon of weapons)for(const [i,environment]of environments.entries())for(const reverse of [false,true])tasks.push({profile,weapon,opponentWeapon,reverse,seed:20264005+i*104729,environment,a:fighter('subject',stats,weapon),b:fighter('opponent',stats,opponentWeapon)});}
 if(['powers','chain'].includes(mode)){const abilities=['No power','Light manipulation','Storm calling','Chain lightning','Arcane silence','Mirror barrier','Portal creation','Shapeshifting','Temporal rewind','Singularity','Phoenix rebirth','Mind reading','Reality bending','Death command','Future sight','Regeneration'];for(const total of [500,1500,2500])for(const weapon of ['Sword','Staff'])for(const ability of mode==='chain'?['Chain lightning']:abilities)for(const opponentAbility of abilities)for(const [i,environment]of environments.entries())for(const reverse of [false,true])tasks.push({total,weapon,ability,opponentAbility,reverse,seed:20263005+i*104729,environment,a:fighter('subject',Array(5).fill(total/5),weapon,ability),b:fighter('opponent',Array(5).fill(total/5),weapon,opponentAbility)});}
 if(mode==='history'){
  const path=process.argv[3];if(!path)throw Error('Pass a decoded audit worlds.json path.');const worlds=JSON.parse(fs.readFileSync(path)).filter(w=>w.phase==='complete'),matches=worlds.flatMap(w=>w.history.map(m=>({w,m})));for(let i=0;i<3000;i++){const {w,m}=matches[Math.floor(i*matches.length/3000)];tasks.push({legacy:true,variant:'v9-replay',seed:m.seed,environment:m.results[0].environment,a:w.roster.find(c=>c.id===m.a),b:w.roster.find(c=>c.id===m.b),expected:m.results[0]});}
  for(const ability of ['Light manipulation','Portal creation'])for(const w of worlds.filter((_,i)=>i%5===0))for(const c of w.roster.filter(c=>[c.traits.power,c.traits.power2].includes(ability))){const matches=w.history.filter(m=>m.phase==='league'&&(m.a===c.id||m.b===c.id));for(let i=0;i<Math.min(12,matches.length);i++){const m=matches[Math.floor(i*matches.length/12)],opponent=w.roster.find(x=>x.id===(m.a===c.id?m.b:m.a));for(const variant of ['with','without']){const a=structuredClone(c);if(variant==='without')for(const slot of ['power','power2'])if(a.traits[slot]===ability)a.traits[slot]=slot==='power'?'No power':'No second power';tasks.push({ability,variant,seed:m.seed,environment:m.results[0].environment,reverse:m.b===c.id,a,b:opponent});}}}
 }
 if(mode==='styles'){
  const worlds=JSON.parse(fs.readFileSync(process.argv[3])).filter(w=>w.phase==='complete'),groups=new Map();
  for(const w of worlds){const roster=new Map(w.roster.map(c=>[c.id,c]));for(const m of w.history.filter(m=>m.phase==='league')){let a=roster.get(m.a),b=roster.get(m.b);const ratio=a.summary.total/b.summary.total;if(ratio<.8||ratio>1.25||combatStyle(a)===combatStyle(b))continue;const priority={arcane:2,ranged:1,melee:0};if(priority[combatStyle(a)]<priority[combatStyle(b)])[a,b]=[b,a];const key=combatStyle(a)+' vs '+combatStyle(b);let list=groups.get(key);if(!list)groups.set(key,list=[]);list.push({a,b,seed:m.seed,environment:m.results[0].environment,reverse:m.b===a.id,comparison:key});}}
  for(const list of groups.values())for(let i=0;i<1500;i++){const t=list[Math.floor(i*list.length/1500)];tasks.push({...t,variant:'v10'},{...t,variant:'v9',legacy:true});}
 }
 const lanes=Math.min(8,Math.max(1,Number(process.env.FATEFORGED_REVIEW_WORKERS)||Math.floor(availableParallelism()/2))),chunks=Array.from({length:lanes},()=>[]);tasks.forEach((t,i)=>chunks[i%lanes].push(t));const worlds=[],rows=[];console.log(`${mode}: ${mode==='worlds'?'10 worlds × 30 seasons':tasks.length+' fights'} · ${lanes} workers`);
 await Promise.all(chunks.map((chunk,i)=>new Promise((resolve,reject)=>{const indices=Array.from({length:10},(_,n)=>n).filter(n=>n%lanes===i),w=new Worker(new URL(import.meta.url),{workerData:{mode,tasks:chunk,indices}});w.on('message',data=>{if(data.progress)console.log(data.progress);if(data.rows)rows.push(...data.rows);if(data.world)worlds.push(data.world);});w.on('error',reject);w.on('exit',code=>code?reject(Error('Evaluation worker failed: '+code)):resolve());})));
 if(mode==='worlds')output({seconds:(performance.now()-began)/1000,worlds:worlds.sort((a,b)=>a.index-b.index)});
 else{const time=rows.map(r=>r.seconds).sort((a,b)=>a-b);output({fights:rows.length,seconds:(performance.now()-began)/1000,replayMatches:rows.filter(r=>r.variant==='v9-replay'&&r.replayMatches).length,medianSeconds:time[Math.floor(time.length*.5)],p90Seconds:time[Math.floor(time.length*.9)],groups:aggregate(rows,['powers','chain'].includes(mode)?['ability','opponentAbility','weapon','total']:mode==='history'?['ability','variant']:mode==='styles'?['comparison','variant']:['profile','weapon','opponentWeapon'])});}
 console.log('Saved '+mode+' evidence.');
}
