// Collects the optional sound files in public/sounds/ for both builds: known cue names only (sound-model.js), OGG,
// MP3 or WAV, effects up to 300 KB and music up to 3 MB. Returns the files to ship and the manifest module that
// tells the arena which cues have a file (the rest keep their generated sound).
import {readdir,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {SOUND_NAMES} from '../public/sound-model.js';
export const SOUND_EXTENSIONS=Object.freeze(['ogg','mp3','wav']);
export const SOUND_MAX_BYTES=Object.freeze({effect:300*1024,music:3*1024*1024});
export async function collectSounds(dir='public/sounds'){
 let entries=[];try{entries=(await readdir(dir)).sort();}catch{}
 const files=[],manifest={},skipped=[];
 for(const file of entries){
  const match=/^(.+)\.([a-z0-9]+)$/.exec(file);if(!match||file==='README.md')continue;const [,name,ext]=match;
  if(!SOUND_NAMES.includes(name)||!SOUND_EXTENSIONS.includes(ext)){skipped.push(`${file}: not a cue name from SOUND.md (.ogg, .mp3 or .wav)`);continue;}
  if(manifest[name]){skipped.push(`${file}: ${name} already has a file`);continue;}
  const data=await readFile(`${dir}/${file}`),limit=name.startsWith('music-')?SOUND_MAX_BYTES.music:SOUND_MAX_BYTES.effect;
  if(data.length>limit){skipped.push(`${file}: ${Math.round(data.length/1024)} KB is over ${limit/1024} KB`);continue;}
  files.push({name,file,data});manifest[name]=`${file}?v=${createHash('sha256').update(data).digest('hex').slice(0,10)}`;
 }
 for(const line of skipped)console.warn('Sound skipped: '+line);
 const module=`// Generated by the build from public/sounds/ (scripts/sounds.mjs).\nexport const SOUND_MANIFEST=${JSON.stringify(manifest)};\n`;
 return {files,manifest,module,skipped};
}
