// Collects the sprite art in public/sprites/ for both builds: known names only (sprite-art.js), WebP or PNG, each
// under SPRITE_MAX_BYTES. Returns the files to ship and the manifest module that tells the renderer what exists.
import {readdir,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {SPRITE_NAMES,SPRITE_EXTENSIONS,SPRITE_MAX_BYTES} from '../public/sprite-art.js';
export async function collectSprites(dir='public/sprites'){
 let entries=[];try{entries=(await readdir(dir)).sort();}catch{}
 const files=[],manifest={},skipped=[];
 for(const file of entries){
  const match=/^(.+)\.([a-z]+)$/.exec(file);if(!match||file==='README.md')continue;const [,name,ext]=match;
  if(!SPRITE_NAMES.includes(name)||!SPRITE_EXTENSIONS.includes(ext)){skipped.push(`${file}: not a sprite name from ART-PROMPTS.md (.webp or .png)`);continue;}
  if(manifest[name]){skipped.push(`${file}: ${name} already has a file`);continue;}
  const data=await readFile(`${dir}/${file}`);
  if(data.length>SPRITE_MAX_BYTES){skipped.push(`${file}: ${Math.round(data.length/1024)} KB is over ${SPRITE_MAX_BYTES/1024} KB; resize to 256 px (512 px for the Titan and pit) and save as WebP`);continue;}
  files.push({name,file,data});manifest[name]=`${file}?v=${createHash('sha256').update(data).digest('hex').slice(0,10)}`;
 }
 for(const line of skipped)console.warn('Sprite skipped: '+line);
 const module=`// Generated by the build from public/sprites/ (scripts/sprites.mjs).\nexport const SPRITE_MANIFEST=${JSON.stringify(manifest)};\n`;
 return {files,manifest,module,skipped};
}
